/*
 * Generated by dtrace(8).
 */

#ifndef	_USER_PROBES_H
#define	_USER_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define	HISTOGRAM_EQUALIZATION_COMPUTING_DONE(arg0) \
	__dtrace_histogram_equalization___computing__done(arg0)
#ifndef	__sparc
#define	HISTOGRAM_EQUALIZATION_COMPUTING_DONE_ENABLED() \
	__dtraceenabled_histogram_equalization___computing__done()
#else
#define	HISTOGRAM_EQUALIZATION_COMPUTING_DONE_ENABLED() \
	__dtraceenabled_histogram_equalization___computing__done(0)
#endif
#define	HISTOGRAM_EQUALIZATION_EQUALIZATION_START(arg0) \
	__dtrace_histogram_equalization___equalization__start(arg0)
#ifndef	__sparc
#define	HISTOGRAM_EQUALIZATION_EQUALIZATION_START_ENABLED() \
	__dtraceenabled_histogram_equalization___equalization__start()
#else
#define	HISTOGRAM_EQUALIZATION_EQUALIZATION_START_ENABLED() \
	__dtraceenabled_histogram_equalization___equalization__start(0)
#endif
#define	HISTOGRAM_EQUALIZATION_MAPPING_DONE(arg0) \
	__dtrace_histogram_equalization___mapping__done(arg0)
#ifndef	__sparc
#define	HISTOGRAM_EQUALIZATION_MAPPING_DONE_ENABLED() \
	__dtraceenabled_histogram_equalization___mapping__done()
#else
#define	HISTOGRAM_EQUALIZATION_MAPPING_DONE_ENABLED() \
	__dtraceenabled_histogram_equalization___mapping__done(0)
#endif
#define	HISTOGRAM_EQUALIZATION_NORMALIZING_DONE(arg0) \
	__dtrace_histogram_equalization___normalizing__done(arg0)
#ifndef	__sparc
#define	HISTOGRAM_EQUALIZATION_NORMALIZING_DONE_ENABLED() \
	__dtraceenabled_histogram_equalization___normalizing__done()
#else
#define	HISTOGRAM_EQUALIZATION_NORMALIZING_DONE_ENABLED() \
	__dtraceenabled_histogram_equalization___normalizing__done(0)
#endif


extern void __dtrace_histogram_equalization___computing__done(int);
#ifndef	__sparc
extern int __dtraceenabled_histogram_equalization___computing__done(void);
#else
extern int __dtraceenabled_histogram_equalization___computing__done(long);
#endif
extern void __dtrace_histogram_equalization___equalization__start(int);
#ifndef	__sparc
extern int __dtraceenabled_histogram_equalization___equalization__start(void);
#else
extern int __dtraceenabled_histogram_equalization___equalization__start(long);
#endif
extern void __dtrace_histogram_equalization___mapping__done(int);
#ifndef	__sparc
extern int __dtraceenabled_histogram_equalization___mapping__done(void);
#else
extern int __dtraceenabled_histogram_equalization___mapping__done(long);
#endif
extern void __dtrace_histogram_equalization___normalizing__done(int);
#ifndef	__sparc
extern int __dtraceenabled_histogram_equalization___normalizing__done(void);
#else
extern int __dtraceenabled_histogram_equalization___normalizing__done(long);
#endif

#else

#define	HISTOGRAM_EQUALIZATION_COMPUTING_DONE(arg0)
#define	HISTOGRAM_EQUALIZATION_COMPUTING_DONE_ENABLED() (0)
#define	HISTOGRAM_EQUALIZATION_EQUALIZATION_START(arg0)
#define	HISTOGRAM_EQUALIZATION_EQUALIZATION_START_ENABLED() (0)
#define	HISTOGRAM_EQUALIZATION_MAPPING_DONE(arg0)
#define	HISTOGRAM_EQUALIZATION_MAPPING_DONE_ENABLED() (0)
#define	HISTOGRAM_EQUALIZATION_NORMALIZING_DONE(arg0)
#define	HISTOGRAM_EQUALIZATION_NORMALIZING_DONE_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _USER_PROBES_H */
